server:
  port: 10002

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/producer?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true

  # rabbitMQ配置
  rabbitmq:
    port: 5672
    username: guest
    password: guest

  #thymeleaf start
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    servlet:
      content-type: text/html
  #thymeleaf end


# mybatis-plus 配置
mybatis-plus:
 global-config:
  db-config:
   id-type: auto
   field-strategy: not_empty
   column-underline: true
   logic-delete-value: 0
   logic-not-delete-value: 1
   db-type: mysql
  refresh: false
 configuration:
  map-underscore-to-camel-case: true
  cache-enabled: false